AWSTemplateFormatVersion: '2010-09-09'
Description: Simple CloudFormation Mapping Example

Mappings:
  EnvToInstanceType:
    dev:
      InstanceType: t2.micro
    test:
      InstanceType: t2.small
    prod:
      InstanceType: t2.medium

Parameters:
  Environment:
    Description: Deployment environment
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Resources:

  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16

  MySubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.1.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !FindInMap
        - EnvToInstanceType
        - !Ref Environment
        - InstanceType
      ImageId: ami-068c0051b15cdb816
      SubnetId: !Ref MySubnet
      SecurityGroupIds:
        - !Ref MySecurityGroup

Outputs:
  SelectedInstanceType:
    Description: Instance type selected from mapping
    Value: !FindInMap
      - EnvToInstanceType
      - !Ref Environment
      - InstanceType
