AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template with Mappings

Mappings:
  RegionToAMIMap:
    us-east-1:
      AMI: ami-068c0051b15cdb816
    us-east-2:
      AMI: ami-00e428798e77d38d9
    eu-west-1:
      AMI: ami-09c54d172e7aa3d9a

Parameters:
  Region:
    Type: String
    Description: AWS region for the EC2 instance
    Default: us-east-1
    AllowedValues:
      - us-east-1
      - us-east-2
      - eu-west-1
#Remember to select the region you are executing it 

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [RegionToAMIMap, !Ref Region, AMI]
